language: node_js
node_js:
- "10"
before_script:
# Install meteor
- curl https://install.meteor.com | /bin/sh
# Add meteor to path (instead of asking for sudo in the Travis container)
# We can then use the faster container infrastructure - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
- export PATH=$HOME/.meteor:$PATH
- npm install -g spacejam
cache:
directories:
- node_modules
